-- MySQL Script generated by MySQL Workbench
-- 08/31/16 22:43:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `member_Id` INT NOT NULL AUTO_INCREMENT,
  `member_FName` VARCHAR(100) NOT NULL,
  `member_LName` VARCHAR(45) NOT NULL,
  `member_Tel` VARCHAR(10) NOT NULL,
  `member_Email` VARCHAR(45) NULL,
  PRIMARY KEY (`member_Id`),
  UNIQUE INDEX `member_Email_UNIQUE` (`member_Email` ASC),
  UNIQUE INDEX `member_UNIQUE` (`member_Tel` ASC),
  UNIQUE INDEX `member_Id_UNIQUE` (`member_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `event_Id` INT NOT NULL AUTO_INCREMENT,
  `event_Topic` VARCHAR(50) NOT NULL,
  `event_Status` INT NOT NULL,
  `event_StartDate` DATE NOT NULL,
  `event_EndDate` DATE NOT NULL,
  `event_AnnouceDate` DATE NULL,
  ` event_NumberofEvent` INT NOT NULL,
  `event_NumberofMember` INT NOT NULL,
  ` event_Time` VARCHAR(50) NULL,
  `event_Location` VARCHAR(45) NULL,
  `event_Description` VARCHAR(500) NOT NULL,
  `event_Picture` BLOB NULL,
  `event_Responseman` VARCHAR(45) NULL,
  `event_ResponsemanTel` INT NULL,
  PRIMARY KEY (`event_Id`),
  UNIQUE INDEX `event_Topic_UNIQUE` (`event_Topic` ASC),
  UNIQUE INDEX `event_Id_UNIQUE` (`event_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`news` ;

CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `news_Id` INT NOT NULL AUTO_INCREMENT,
  `news_Topic` VARCHAR(45) NULL,
  `news_Type` VARCHAR(45) NULL,
  `news_Relese` DATE NULL,
  `news_Date` DATE NULL,
  `news_Descriptiom` VARCHAR(500) NULL,
  `news_Picture` BLOB NULL,
  PRIMARY KEY (`news_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_FName` VARCHAR(50) NOT NULL,
  `admin_LName` VARCHAR(45) NOT NULL,
  `admin_Email` VARCHAR(45) NOT NULL,
  `admin_Tel` VARCHAR(10) NOT NULL,
  `admin_Username` VARCHAR(20) NOT NULL,
  `admin_Password` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`admin_Id`),
  UNIQUE INDEX `staff_Username_UNIQUE` (`admin_Username` ASC),
  UNIQUE INDEX `staff_Tel_UNIQUE` (`admin_Tel` ASC),
  UNIQUE INDEX `staff_Email_UNIQUE` (`admin_Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`authority` ;

CREATE TABLE IF NOT EXISTS `mydb`.`authority` (
  `author_Id` INT NOT NULL AUTO_INCREMENT,
  `author_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`author_Id`),
  UNIQUE INDEX `Author_Name_UNIQUE` (`author_Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`audio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`audio` (
  `audio_Id` INT NOT NULL AUTO_INCREMENT,
  `audio_Date` DATE NOT NULL,
  `audio_ViewCount` INT NOT NULL,
  `audio_File` BLOB NOT NULL,
  PRIMARY KEY (`audio_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`history_register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`history_register` ;

CREATE TABLE IF NOT EXISTS `mydb`.`history_register` (
  `hisRegis_Id` INT NOT NULL AUTO_INCREMENT,
  `hisRegis_AmountPerTime` INT NOT NULL,
  `hisRegis_AmountTotal` INT NOT NULL,
  `hisRegis_Date` DATETIME NULL,
  `member_member_Id` INT NOT NULL,
  `event_event_Id` INT NOT NULL,
  PRIMARY KEY (`hisRegis_Id`, `member_member_Id`, `event_event_Id`),
  UNIQUE INDEX `hisRegis_Id_UNIQUE` (`hisRegis_Id` ASC),
  INDEX `fk_history_register_member1_idx` (`member_member_Id` ASC),
  INDEX `fk_history_register_event1_idx` (`event_event_Id` ASC),
  CONSTRAINT `fk_history_register_member1`
    FOREIGN KEY (`member_member_Id`)
    REFERENCES `mydb`.`member` (`member_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_register_event1`
    FOREIGN KEY (`event_event_Id`)
    REFERENCES `mydb`.`event` (`event_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `tag_Id` INT NOT NULL AUTO_INCREMENT,
  `tag_Name` VARCHAR(100) NOT NULL,
  `tag_Type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tag_Id`),
  UNIQUE INDEX `tag_name_UNIQUE` (`tag_Name` ASC),
  UNIQUE INDEX `tag_Type_UNIQUE` (`tag_Type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audio_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`audio_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`audio_tag` (
  `audTag_Id` INT NOT NULL AUTO_INCREMENT,
  `audio_audio_Id` INT NOT NULL,
  `tag_tag_Id` INT NOT NULL,
  PRIMARY KEY (`audTag_Id`, `audio_audio_Id`, `tag_tag_Id`),
  INDEX `fk_audio_tag_audio1_idx` (`audio_audio_Id` ASC),
  INDEX `fk_audio_tag_tag1_idx` (`tag_tag_Id` ASC),
  CONSTRAINT `fk_audio_tag_audio1`
    FOREIGN KEY (`audio_audio_Id`)
    REFERENCES `mydb`.`audio` (`audio_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audio_tag_tag1`
    FOREIGN KEY (`tag_tag_Id`)
    REFERENCES `mydb`.`tag` (`tag_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event_tag` (
  `eventTag_Id` INT NOT NULL AUTO_INCREMENT,
  `tag_tag_Id` INT NOT NULL,
  `event_event_Id` INT NOT NULL,
  PRIMARY KEY (`eventTag_Id`, `tag_tag_Id`, `event_event_Id`),
  INDEX `fk_event_tag_tag1_idx` (`tag_tag_Id` ASC),
  INDEX `fk_event_tag_event1_idx` (`event_event_Id` ASC),
  CONSTRAINT `fk_event_tag_tag1`
    FOREIGN KEY (`tag_tag_Id`)
    REFERENCES `mydb`.`tag` (`tag_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_tag_event1`
    FOREIGN KEY (`event_event_Id`)
    REFERENCES `mydb`.`event` (`event_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`news_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`news_tag` (
  `newsTag_Id` INT NOT NULL AUTO_INCREMENT,
  `tag_tag_Id` INT NOT NULL,
  `news_news_Id` INT NOT NULL,
  PRIMARY KEY (`newsTag_Id`, `tag_tag_Id`, `news_news_Id`),
  INDEX `fk_news_tag_tag1_idx` (`tag_tag_Id` ASC),
  INDEX `fk_news_tag_news1_idx` (`news_news_Id` ASC),
  CONSTRAINT `fk_news_tag_tag1`
    FOREIGN KEY (`tag_tag_Id`)
    REFERENCES `mydb`.`tag` (`tag_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_tag_news1`
    FOREIGN KEY (`news_news_Id`)
    REFERENCES `mydb`.`news` (`news_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_manage_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_manage_event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_manage_event` (
  `manageEvent_Id` INT NOT NULL AUTO_INCREMENT,
  `event_event_Id` INT NOT NULL,
  `admin_admin_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`manageEvent_Id`, `event_event_Id`, `admin_admin_Id`),
  INDEX `fk_admin_manage_event_event1_idx` (`event_event_Id` ASC),
  INDEX `fk_admin_manage_event_admin1_idx` (`admin_admin_Id` ASC),
  CONSTRAINT `fk_admin_manage_event_event1`
    FOREIGN KEY (`event_event_Id`)
    REFERENCES `mydb`.`event` (`event_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_manage_event_admin1`
    FOREIGN KEY (`admin_admin_Id`)
    REFERENCES `mydb`.`admin` (`admin_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_mange_news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_mange_news` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_mange_news` (
  `mangeNews_Id` INT NOT NULL AUTO_INCREMENT,
  `news_news_Id` INT NOT NULL,
  `admin_admin_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`mangeNews_Id`, `news_news_Id`, `admin_admin_Id`),
  INDEX `fk_admin_mange_news_news1_idx` (`news_news_Id` ASC),
  INDEX `fk_admin_mange_news_admin1_idx` (`admin_admin_Id` ASC),
  CONSTRAINT `fk_admin_mange_news_news1`
    FOREIGN KEY (`news_news_Id`)
    REFERENCES `mydb`.`news` (`news_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_mange_news_admin1`
    FOREIGN KEY (`admin_admin_Id`)
    REFERENCES `mydb`.`admin` (`admin_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_manage_audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_manage_audio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_manage_audio` (
  `manageAudio_Idl` INT NOT NULL AUTO_INCREMENT,
  `audio_audio_Id` INT NOT NULL,
  `admin_admin_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`manageAudio_Idl`, `audio_audio_Id`, `admin_admin_Id`),
  INDEX `fk_admin_manage_audio_audio1_idx` (`audio_audio_Id` ASC),
  INDEX `fk_admin_manage_audio_admin1_idx` (`admin_admin_Id` ASC),
  CONSTRAINT `fk_admin_manage_audio_audio1`
    FOREIGN KEY (`audio_audio_Id`)
    REFERENCES `mydb`.`audio` (`audio_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_manage_audio_admin1`
    FOREIGN KEY (`admin_admin_Id`)
    REFERENCES `mydb`.`admin` (`admin_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_manage_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_manage_member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_manage_member` (
  `manageMember_Id` INT NOT NULL AUTO_INCREMENT,
  `manageMember_Date` DATE NULL,
  `member_member_Id` INT NOT NULL,
  `admin_admin_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`manageMember_Id`, `member_member_Id`, `admin_admin_Id`),
  INDEX `fk_admin_manage_member_member1_idx` (`member_member_Id` ASC),
  INDEX `fk_admin_manage_member_admin1_idx` (`admin_admin_Id` ASC),
  CONSTRAINT `fk_admin_manage_member_member1`
    FOREIGN KEY (`member_member_Id`)
    REFERENCES `mydb`.`member` (`member_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_manage_member_admin1`
    FOREIGN KEY (`admin_admin_Id`)
    REFERENCES `mydb`.`admin` (`admin_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `role_Id` INT NOT NULL AUTO_INCREMENT,
  `role_Name` VARCHAR(45) NOT NULL,
  `admin_admin_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_Id`, `admin_admin_Id`),
  UNIQUE INDEX `role__UNIQUE` (`role_Name` ASC),
  INDEX `fk_role_admin1_idx` (`admin_admin_Id` ASC),
  CONSTRAINT `fk_role_admin1`
    FOREIGN KEY (`admin_admin_Id`)
    REFERENCES `mydb`.`admin` (`admin_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role_authority` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role_authority` (
  `roleAuthor_Id` INT NOT NULL AUTO_INCREMENT,
  `authority_author_Id` INT NOT NULL,
  `role_role_Id` INT NOT NULL,
  PRIMARY KEY (`roleAuthor_Id`, `authority_author_Id`, `role_role_Id`),
  INDEX `fk_role_authority_authority1_idx` (`authority_author_Id` ASC),
  INDEX `fk_role_authority_role1_idx` (`role_role_Id` ASC),
  CONSTRAINT `fk_role_authority_authority1`
    FOREIGN KEY (`authority_author_Id`)
    REFERENCES `mydb`.`authority` (`author_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_authority_role1`
    FOREIGN KEY (`role_role_Id`)
    REFERENCES `mydb`.`role` (`role_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event_picture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event_picture` (
  `eventpicture_Id` INT NOT NULL AUTO_INCREMENT,
  `eventpicture_file` BLOB NULL,
  `event_event_Id` INT NOT NULL,
  PRIMARY KEY (`eventpicture_Id`, `event_event_Id`),
  INDEX `fk_event_picture_event1_idx` (`event_event_Id` ASC),
  CONSTRAINT `fk_event_picture_event1`
    FOREIGN KEY (`event_event_Id`)
    REFERENCES `mydb`.`event` (`event_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
